apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leargon.fullname" . }}-backend
  labels:
    {{- include "leargon.backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ required "backend.jwt.secret is required" .Values.backend.jwt.secret | b64enc | quote }}
  admin-password: {{ .Values.backend.admin.password | b64enc | quote }}
  {{- if .Values.mysql.enabled }}
  db-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
