apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "leargon.fullname" . }}-frontend
  labels:
    {{- include "leargon.frontend.labels" . | nindent 4 }}
data:
  VITE_API_URL: "http://{{ include "leargon.fullname" . }}-backend:{{ .Values.backend.service.port }}"
