{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leargon.fullname" . }}-mysql
  labels:
    {{- include "leargon.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}
